---
production:
  S3:
    access_key_id: THES3KEY
    secret_access_key: the/S3/secret0access+key
    bucket: the.s3.bucket
  tootsie: http://localhost:9000

staging:
  S3:
    access_key_id: THES3KEY
    secret_access_key: the/S3/secret0access+key
    bucket: the.s3.bucket
  tootsie: http://localhost:9000

development:
  S3:
    access_key_id: THES3KEY
    secret_access_key: the/S3/secret0access+key
    bucket: the.s3.bucket
  tootsie: http://localhost:9000
